services:
  auto-rag:
    build:
      platforms:
        - linux/amd64
      context: ../
      dockerfile: .deploy/Dockerfile
    env_file:
      - .env
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ../:/app
    restart: always
    depends_on:
      - otel-collector
      - postgres
    develop:
      watch:
        - action: sync+restart
          path: ../
          target: /app
          ignore:
            - node_modules/
            - .git/

    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 8080 || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 2
      start_period: 60s
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 30s
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://auto-rag:8080
    tty: true
    restart: always
    depends_on:
      - auto-rag

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "6831:6831" # Jaeger receiver
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
    restart: always

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: embeddings_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  #vllm:
  #  image: vllm/vllm-openai:latest
  #  runtime: nvidia
  #  environment:
  #    - HUGGING_FACE_HUB_TOKEN=<secret>
  #  volumes:
  #    - ~/.cache/huggingface:/root/.cache/huggingface
  #  ports:
  #    - "8000:8000"
  #  ipc: host
  # command: --model mistralai/Mistral-7B-v0.1
  #  deploy:
  #    resources:
  #      reservations:
  #        devices:
  #          - driver: nvidia
  #           count: all

volumes:
  postgres_data:
